Adding COMBLE-MIP tutorial
ARM-Development/arm-summer-school-2024 pull request #23
Opened 2024-05-06 20:46 UTC by twjuliano

Including notebook for tutorial, as well as supporting script that contains functions and data files needed to run tutorial.

2024-05-06 21:02 UTC, twjuliano commented
@mgrover1 looks like it is barking at the `glob` dependency.

2024-05-06 21:12 UTC, mgrover1 requested changes
one small fix

2024-05-06 21:12 UTC, mgrover1 commented on environment.yml
> +  - glob
```suggestion
```

glob is included by default

2024-05-07 13:28 UTC, mgrover1 approved these changes

2024-05-08 14:45 UTC, mgrover1 commented
this looks great @twjuliano - do you have access to cumulus?

2024-05-08 14:46 UTC, twjuliano commented
> this looks great @twjuliano - do you have access to cumulus?

@mgrover1 thanks! yes, I have access to cumulus

2024-05-08 14:48 UTC, mgrover1 commented
Any chance you could move the files you added here to that data folder on cumulus? 

`/gpfs/wolf2/arm/atm124/world-shared/arm-summer-school-2024`

2024-05-08 14:48 UTC, mgrover1 commented
Mainly just thinking about the size of the gitlog with the large files

2024-05-08 15:10 UTC, mgrover1 approved these changes

2024-05-08 15:23 UTC, mgrover1 commented
@twjuliano thanks for making those changes! Good to merge?

2024-05-08 15:24 UTC, twjuliano commented
> @twjuliano thanks for making those changes! Good to merge?

@mgrover1 I say go for it!

2024-05-08 15:30 UTC, merged